server:
  port: 9002
spring:
  application:
    name: healthy-coupon-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
  rabbitmq:
    host: 121.199.42.235
    port: 5672
    virtual-host: /
    password: password
    username: admin
    #开启⼿动确认消息
    listener:
      simple:
       acknowledge-mode: manual
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.199.42.235:3306/healthy_mall_coupon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: abc123456
  redis:
    host: 121.199.42.235
    password: 123456
    port: 8000
#配置plus打印sql⽇志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #设置⽇志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO
#seata:
  #tx-service-group: ${spring.application.name}-group
  #service:
    #grouplist:
      #gosenor-healthy: 127.0.0.1:8091
    #vgroup-mapping:
      #healthy-coupon-service-group: gosenor-healthy


mqconfig:
  #延迟队列，不能被监听消费
  coupon_release_delay_queue: coupon.release.delay.queue
  #延迟队列的消息过期后转发的队列
  coupon_release_queue: coupon.release.queue
  #交换机
  coupon_event_exchange: coupon.event.exchange
  #进⼊延迟队列的路由key
  coupon_release_delay_routing_key: coupon.release.delay.routing.key
  #消息过期，进⼊释放死信队列的key
  coupon_release_routing_key: coupon.release.routing.key
  #消息过期时间,毫秒,测试改为15秒
  ttl: 15000